7.Workshop/petstagram/petstagram/petstagram/common/urls.py
from django.urls import path

from petstagram.common.views import index, like_photo, share_photo, comment_photo

urlpatterns = (
    path('', index, name='index'),
    path('like/<int:photo_id>/', like_photo, name='like photo'),
    path('share/<int:photo_id>/', share_photo, name='share photo'),
    path('comment/<int:photo_id>/', comment_photo, name='comment photo'),
)

7.Workshop/petstagram/petstagram/petstagram/pets/urls.py
from django.urls import path, include

from petstagram.pets.views import add_pet, details_pet, edit_pet, delete_pet

urlpatterns = (
    path('add/', add_pet, name='add pet'),
    path('<str:username>/pet/<slug:pet_slug>/', include([
        path('', details_pet, name='details pet'),
        path('edit/', edit_pet, name='edit pet'),
        path('delete/', delete_pet, name='delete pet'),
    ]))
)

7.Workshop/petstagram/petstagram/petstagram/photos/urls.py
from django.urls import path, include

from petstagram.photos.views import add_photo, details_photo, edit_photo, delete_photo

urlpatterns = (
    path('add/', add_photo, name='add photo'),
    path('<int:pk>/', include([
        path('', details_photo, name='details photo'),
        path('edit/', edit_photo, name='edit photo'),
        path('delete/', delete_photo, name='delete photo'),
    ])),
)

7.Workshop/petstagram/petstagram/petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls')),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls')),
]

7.Workshop/petstagram/petstagram/petstagram/accounts/models.py
from enum import Enum

from django.contrib.auth import models as auth_models
from django.core import validators
from django.db import models

from petstagram.core.model_mixins import ChoicesEnumMixin
from petstagram.core.validators import validate_only_letters


class Gender(ChoicesEnumMixin, Enum):
    male = 'Male'
    female = 'Female'
    DoNotShow = 'Do no show'


class AppUser(auth_models.AbstractUser):
    MIN_LEN_FIRST_NAME = 2
    MAX_LEN_FIRST_NAME = 30
    MIN_LEN_LAST_NAME = 2
    MAX_LEN_LAST_NAME = 30

    first_name = models.CharField(
        max_length=MAX_LEN_FIRST_NAME,
        validators=(
            validators.MinLengthValidator(MIN_LEN_FIRST_NAME),
            validate_only_letters,
        )
    )

    last_name = models.CharField(
        max_length=MAX_LEN_LAST_NAME,
        validators=(
            validators.MinLengthValidator(MIN_LEN_LAST_NAME),
            validate_only_letters,
        )
    )

    email = models.EmailField(
        unique=True,
    )

    gender = models.CharField(
        choices=Gender.choices(),
        max_length=Gender.max_len(),
    )

    # is_verified = models.BooleanField(
    #     default=False,
    # )

    # Users log in with `email`
    # USERNAME_FIELD = 'email'

7.Workshop/petstagram/petstagram/petstagram/common/models.py
from django.contrib.auth import get_user_model
from django.db import models

from petstagram.photos.models import Photo

UserModel = get_user_model()


class PhotoComment(models.Model):
    MAX_TEXT_LENGTH = 300
    text = models.CharField(
        max_length=MAX_TEXT_LENGTH,
        null=False,
        blank=False,
    )

    publication_date_and_time = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=False,
    )

    photo = models.ForeignKey(
        Photo,
        on_delete=models.RESTRICT,
        null=False,
        blank=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )


class PhotoLike(models.Model):
    # Photo's field for likes is named `{NAME_OF_THIS_MODEL.lower()}_set`
    photo = models.ForeignKey(
        Photo,
        on_delete=models.RESTRICT,
        null=False,
        blank=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )

7.Workshop/petstagram/petstagram/petstagram/accounts/forms.py
from django.contrib.auth import forms as auth_forms, get_user_model

UserModel = get_user_model()


class UserEditForm(auth_forms.UserChangeForm):
    class Meta:
        model = UserModel
        fields = ('first_name',)
        field_classes = {'username': auth_forms.UsernameField}


class UserCreateForm(auth_forms.UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email')
        field_classes = {
            'username': auth_forms.UsernameField,
        }

7.Workshop/petstagram/petstagram/petstagram/common/forms.py
from django import forms

from petstagram.common.models import PhotoComment


class PhotoCommentForm(forms.ModelForm):
    class Meta:
        model = PhotoComment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(
                attrs={
                    'cols': 40,
                    'rows': 10,
                    'placeholder': 'Add comment...'
                },
            ),
        }


class SearchPhotosForm(forms.Form):
    pet_name = forms.CharField(
        max_length=50,
        required=False,
    )

7.Workshop/petstagram/petstagram/petstagram/pets/forms.py
from django import forms

from petstagram.core.form_mixins import DisabledFormMixin
from petstagram.pets.models import Pet


# `ModelForm` and `Form`:
# - `ModelForm` binds to models
# - `Form` is detached from models

class PetBaseForm(forms.ModelForm):
    class Meta:
        model = Pet
        # fields = '__all__' (not the case, we want to skip `slug`
        fields = ('name', 'date_of_birth', 'personal_photo')
        # exclude = ('slug',)
        labels = {
            'name': 'Pet Name',
            'personal_photo': 'Link to Image',
            'date_of_birth': 'Date of Birth',
        }
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Pet name'
                }
            ),
            'date_of_birth': forms.DateInput(
                attrs={
                    'placeholder': 'mm/dd/yyyy',
                    'type': 'date',
                }
            ),
            'personal_photo': forms.URLInput(
                attrs={
                    'placeholder': 'Link to image',
                }
            )
        }


class PetCreateForm(PetBaseForm):
    pass


class PetEditForm(DisabledFormMixin, PetBaseForm):
    disabled_fields = ('name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._disable_fields()


class PetDeleteForm(DisabledFormMixin, PetBaseForm):
    disabled_fields = ('name', 'date_of_birth', 'personal_photo')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._disable_fields()


    def save(self, commit=True):
        if commit:
            self.instance.delete()
        return self.instance

7.Workshop/petstagram/petstagram/petstagram/photos/forms.py
from django import forms
from django.core.exceptions import ValidationError

from petstagram.common.models import PhotoLike, PhotoComment
from petstagram.core.form_mixins import DisabledFormMixin
from petstagram.photos.models import Photo


class PhotoBaseForm(forms.ModelForm):
    class Meta:
        model = Photo
        exclude = ('publication_date', 'user')


class PhotoCreateForm(PhotoBaseForm):
    pass


class PhotoEditForm(PhotoBaseForm):
    class Meta:
        model = Photo
        exclude = ('publication_date', 'photo')


class PhotoDeleteForm(DisabledFormMixin, PhotoBaseForm):
    disabled_fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        if commit:
            self.instance.tagged_pets.clear()  # many-to-many

            Photo.objects.all() \
                .first().tagged_pets.clear()
            PhotoLike.objects.filter(photo_id=self.instance.id) \
                .delete()  # one-to-many
            PhotoComment.objects.filter(photo_id=self.instance.id) \
                .delete()  # one-to-many
            self.instance.delete()

        return self.instance

7.Workshop/petstagram/petstagram/petstagram/accounts/views.py
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth import views as auth_views, get_user_model, login

from petstagram.accounts.forms import UserCreateForm
from petstagram.photos.models import Photo

# Always get the *user model* with `get_user_model`
UserModel = get_user_model()


class SignInView(auth_views.LoginView):
    template_name = 'accounts/login-page.html'


class SignUpView(views.CreateView):
    template_name = 'accounts/register-page.html'
    form_class = UserCreateForm
    success_url = reverse_lazy('index')

    def post(self, request, *args, **kwargs):
        response = super().post(request, *args, **kwargs)
        login(request, self.object)
        return response


class SignOutView(auth_views.LogoutView):
    next_page = reverse_lazy('index')


class UserDetailsView(views.DetailView):
    template_name = 'accounts/profile-details-page.html'
    model = UserModel
    photos_paginate_by = 2

    def get_photos_page(self):
        return self.request.GET.get('page', 1)

    def get_paginated_photos(self):
        page = self.get_photos_page()

        photos = self.object.photo_set \
            .order_by('-publication_date')

        paginator = Paginator(photos, self.photos_paginate_by)
        return paginator.get_page(page)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['is_owner'] = self.request.user == self.object
        context['pets_count'] = self.object.pet_set.count()

        photos = self.object.photo_set \
            .prefetch_related('photolike_set')

        context['photos_count'] = photos.count()
        context['likes_count'] = sum(x.photolike_set.count() for x in photos)

        context['photos'] = self.get_paginated_photos()
        context['pets'] = self.object.pet_set.all()

        return context


class UserEditView(views.UpdateView):
    template_name = 'accounts/profile-edit-page.html'
    model = UserModel
    fields = ('first_name', 'last_name', 'gender', 'email',)

    def get_success_url(self):
        return reverse_lazy('details user', kwargs={
            'pk': self.request.user.pk,
        })


class UserDeleteView(views.DeleteView):
    template_name = 'accounts/profile-delete-page.html'
    model = UserModel
    success_url = reverse_lazy('index')

7.Workshop/petstagram/petstagram/petstagram/common/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, resolve_url
import pyperclip
from django.urls import reverse

from petstagram.common.forms import PhotoCommentForm, SearchPhotosForm
from petstagram.common.models import PhotoLike
from petstagram.common.utils import get_photo_url
from petstagram.core.photo_utils import apply_likes_count, apply_user_liked_photo
from petstagram.photos.models import Photo


def index(request):
    search_form = SearchPhotosForm(request.GET)
    search_pattern = None
    if search_form.is_valid():
        search_pattern = search_form.cleaned_data['pet_name']

    photos = Photo.objects.all()

    if search_pattern:
        photos = photos.filter(tagged_pets__name__icontains=search_pattern)

    photos = [apply_likes_count(photo) for photo in photos]
    photos = [apply_user_liked_photo(photo) for photo in photos]
    print(photos)
    context = {
        'photos': photos,
        'comment_form': PhotoCommentForm(),
        'search_form': search_form,
    }

    return render(
        request,
        'common/home-page.html',
        context,
    )


@login_required
def like_photo(request, photo_id):
    user_liked_photos = PhotoLike.objects \
        .filter(photo_id=photo_id, user_id=request.user.pk)

    if user_liked_photos:
        user_liked_photos.delete()
    else:
        PhotoLike.objects.create(
            photo_id=photo_id,
            user_id=request.user.pk,
        )

    return redirect(get_photo_url(request, photo_id))


def share_photo(request, photo_id):
    photo_details_url = reverse('details photo', kwargs={
        'pk': photo_id
    })
    pyperclip.copy(photo_details_url)
    return redirect(get_photo_url(request, photo_id))


@login_required
def comment_photo(request, photo_id):
    photo = Photo.objects.filter(pk=photo_id) \
        .get()

    form = PhotoCommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)  # Does not persist to DB
        comment.photo = photo
        comment.save()

    return redirect('index')

7.Workshop/petstagram/petstagram/petstagram/pets/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from petstagram.core.photo_utils import apply_likes_count, apply_user_liked_photo
from petstagram.core.utils import is_owner
from petstagram.pets.forms import PetCreateForm, PetEditForm, PetDeleteForm
from petstagram.pets.utils import get_pet_by_name_and_username


def details_pet(request, username, pet_slug):
    pet = get_pet_by_name_and_username(pet_slug, username)
    photos = [apply_likes_count(photo) for photo in pet.photo_set.all()]
    photos = [apply_user_liked_photo(photo) for photo in photos]

    context = {
        'pet': pet,
        'photos_count': pet.photo_set.count(),
        'pet_photos': photos,
        'is_owner': pet.user == request.user,
    }

    return render(
        request,
        'pets/pet-details-page.html',
        context,
    )


@login_required
def add_pet(request):
    if request.method == 'GET':
        form = PetCreateForm()
    else:
        form = PetCreateForm(request.POST)
        if form.is_valid():
            pet = form.save(commit=False)
            pet.user = request.user
            pet.save()
            return redirect('details user', pk=request.user.pk)

    context = {
        'form': form,
    }

    return render(request, 'pets/pet-add-page.html', context)


def edit_pet(request, username, pet_slug):
    pet = get_pet_by_name_and_username(pet_slug, username)

    if not is_owner(request, pet):
        return redirect('details pet', username=username, pet_slug=pet_slug)

    if request.method == 'GET':
        form = PetEditForm(instance=pet)
    else:
        form = PetEditForm(request.POST, instance=pet)
        if form.is_valid():
            form.save()
            return redirect('details pet', username=username, pet_slug=pet_slug)

    context = {
        'form': form,
        'pet_slug': pet_slug,
        'username': username,
    }

    return render(
        request,
        'pets/pet-edit-page.html',
        context,
    )


def delete_pet(request, username, pet_slug):
    pet = get_pet_by_name_and_username(pet_slug, username)

    if request.method == 'GET':
        form = PetDeleteForm(instance=pet)
    else:
        form = PetDeleteForm(request.POST, instance=pet)
        if form.is_valid():
            form.save()
            return redirect('details user', pk=1)

    context = {
        'form': form,
        'pet_slug': pet_slug,
        'username': username,
    }

    return render(
        request,
        'pets/pet-delete-page.html',
        context,
    )

7.Workshop/petstagram/petstagram/petstagram/photos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from petstagram.photos.forms import PhotoCreateForm, PhotoEditForm, PhotoDeleteForm
from petstagram.photos.models import Photo


def details_photo(request, pk):
    photo = Photo.objects.filter(pk=pk) \
        .get()

    user_like_photos = Photo.objects.filter(pk=pk, user_id=request.user.pk)

    context = {
        'photo': photo,
        'has_user_liked_photo': user_like_photos,
        'likes_count': photo.photolike_set.count(),
        'is_owner': request.user == photo.user,
    }

    return render(
        request,
        'photos/photo-details-page.html',
        context,
    )


def get_post_photo_form(request, form, success_url, template_path, pk=None):
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(success_url)

    context = {
        'form': form,
        'pk': pk,
    }

    return render(request, template_path, context)


@login_required
def add_photo(request):
    if request.method == 'GET':
        form = PhotoCreateForm()
    else:
        form = PhotoCreateForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.user = request.user
            photo.save()
            form.save_m2m()

            return redirect('details photo', pk=photo.pk)

    context = {
        'form': form,
    }

    return render(
        request,
        'photos/photo-add-page.html',
        context,
    )


def edit_photo(request, pk):
    photo = Photo.objects.filter(pk=pk) \
        .get()
    return get_post_photo_form(
        request,
        PhotoEditForm(request.POST or None, instance=photo),
        success_url=reverse('index'),
        template_path='photos/photo-edit-page.html',
        pk=pk,
    )


def delete_photo(request, pk):
    photo = Photo.objects.filter(pk=pk) \
        .get()
    return get_post_photo_form(
        request,
        PhotoDeleteForm(request.POST or None, instance=photo),
        success_url=reverse('index'),
        template_path='photos/photo-delete-page.html',
        pk=pk,
    )

7.Workshop/petstagram/petstagram/templates/partials/photo-item.html
{% load static %}

<div class="card">
    <div class="top">
        <div class="userDetails">
            <!-- Link to User Profile Page -->
            <a href="#">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="{% static 'images/person.png' %}" alt="img8">
                        </div>
                    </div>
                </div>
            </a>
            <h3>
                <!-- Link to User Profile Page -->
                <a href="{% url 'details user' pk=1 %}">
                    <!-- if user has first name and last name -->
                    Diyan Kalaydzhiev
                    <!-- else -->
                    <!-- show user username -->
                </a>
                <br>
                {% if photo.location %}
                    <span>{{ photo.location }}</span>
                {% endif %}
            </h3>
        </div>
    </div>

    <div class="imgBx" id="photo-{{ photo.pk }}">
        <img src="{{ photo.photo.url }}" alt="post" class="cover">
    </div>

    <div class="bottom">
        <div class="actionBtns">
            <div class="left">
                <span class="heart">
                    <a href="{% url 'like photo' photo_id=photo.pk %}">
                        {% if photo.is_liked_by_user %}
                            <svg style="color: red"
                                 xmlns="http://www.w3.org/2000/svg"
                                 width="24"
                                 height="24"
                                 fill="currentColor"
                                 class="bi bi-heart-fill"
                                 viewBox="0 0 16 16">
                            <!-- Coordinate path -->
                            <path fill-rule="evenodd"
                                  d="M8 1.314C12.438-3.248 23.534 4.735
                                  8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                  fill="red">

                            </path>
                        </svg>
                        {% else %}
                            <svg aria-label="Like"
                                 color="#262626"
                                 fill="#262626"
                                 height="24"
                                 role="img"
                                 viewBox="0 0 48 48"
                                 width="24">
                        <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                    11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                    41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                    11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                    1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                    1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                    1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                    0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                    1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                    1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                    7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                    48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                        </path>
                    </svg>
                        {% endif %}
                    </a>
                </span>
                <a href="{% url 'share photo' photo_id=photo.pk %}">
                    <svg aria-label="Share Post" class="_8-yf5 " color="#262626" fill="#262626"
                         height="24" role="img" viewBox="0 0 48 48" width="24">
                        <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3
										3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6
										1 1.2 1.1h.2c.5 0 1-.3
										1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2
										6.1h35.5L18 18.7 5.2 6.1zm18.7
										33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
                        </path>
                    </svg>
                </a>
            </div>
        </div>
        <p class="likes">{{ photo.likes_count }} likes</p>

        {% for pet in photo.tagged_pets.all %}
            {# TODO: change username to actual user when auth is available #}
            <a href="{% url 'details pet' username='doncho' pet_slug=pet.slug %}">
                <p class="message">
                    <b>{{ pet.name }}</b>
                </p>
            </a>
        {% endfor %}

        <!-- Link to Photo Details Page -->
        <a href="{% url 'details photo' pk=photo.pk %}">
            <h4 class="details">See details</h4>
        </a>

        <!-- Date of Publication -->
        <h5 class="postTime">{{ photo.publication_date }}</h5>

        {% for comment in photo.photocomment_set.all %}
            <div class="comments">
                <div class="top">
                    <div class="userDetails">
                        <div class="comment-data">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="{% static 'images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                            <p>
                                {# TODO: fix with auth #}
                                <a href="">Steven Ivanov</a>
                                <!-- User Comment -->
                                {{ comment.text }}

                            </p>
                        </div>
                        <span>{{ comment.publication_date }}</span>
                    </div>
                </div>
            </div>
            <!-- End Comments Section -->
        {% endfor %}


        <div class="addComments">
            <div class="reaction">
                <h3>
                    <i class="far fa-smile"></i>
                </h3>
            </div>
                <form method="post" action="{% url 'comment photo' photo_id=photo.pk %}">
                    {{ comment_form }}
                    <button type="submit">Post</button>
                    {% csrf_token %}
                </form>
            </form>
        </div>
    </div>
</div>